
INSERT INTO ALIEN VALUES(1, 'MUEBLES','SOFAS');
INSERT INTO ALIEN VALUES(2, 'VIEJO','REY');
INSERT INTO ALIEN VALUES(3, 'CIERVO','FANTASMA');
INSERT INTO ALIEN VALUES(4, 'SAN PEDRO SULA','CORTES');
INSERT INTO ALIEN VALUES(5, 'ELVIS PRESLEY','REY');
